[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
n_prb = 25

[rf]
dl_earfcn = 3350
tx_gain = 40
rx_gain = 20
device_name = soapy
device_args = driver=plutosdr,uri=usb:<id_pluto_enb>

[pcap]
s1ap_enable = true
s1ap_filename = logs/pluto/enb_pluto_s1ap.pcap

[log]
all_level = info
filename = logs/pluto/enb_pluto.log
