[mme]
mme_code = 0x1a
mme_group = 0x0001
tac = 0x0007
mcc = 001
mnc = 01
mme_bind_addr = 127.0.1.100
apn = srsapn
dns_addr = 8.8.8.8
encryption_algo = EEA0
integrity_algo = EIA1

[hss]
db_file = logs/pluto/user_db.sanitized.csv

[spgw]
gtpu_bind_addr = 127.0.1.100
sgi_if_addr = 172.16.0.1
sgi_if_name = srs_spgw_sgi

[pcap]
enable = true
filename = logs/pluto/epc_vm.pcap

[log]
all_level = info
filename = logs/pluto/epc_vm.log
