[rf]
freq_offset = 4500
tx_gain = 80
rx_gain = 70
device_name = soapy
device_args = driver=plutosdr,uri=usb:<id_pluto_ue>

[rat.eutra]
dl_earfcn = 3350
dl_freq = 2680000000
ul_freq = 2560000000

[pcap]
enable = nas
nas_filename = logs/pluto/ue_pluto_nas.pcap

[usim]
mode = soft
algo = milenage
imsi = <masqué>
imei = <masqué>
k = <masqué>
opc = <masqué>

[nas]
apn = srsapn
apn_protocol = ipv4

[gw]
ip_devname = tun_srsue
ip_netmask = 255.255.255.0
