; Extrait assaini du plan de numérotation Asterisk.

[interne]
; Appel interne vers Fanvil
exten => 1012,1,Dial(PJSIP/FanvilXX,12)
same => n,VoiceMail(${EXTEN}@default,u)
same => n,Hangup()

; Appel interne vers Cisco
exten => 2012,1,Dial(PJSIP/CiscoXX,12)
same => n,VoiceMail(${EXTEN}@default,u)
same => n,Hangup()

; Accès centralisé à la messagerie
exten => 888,1,VoiceMailMain(${CALLERID(num)}@default)
same => n,Hangup()

; Entrée du serveur vocal interactif
exten => 0800,1,Answer()
same => n,Goto(AccueilAnnonce,s,1)

[AccueilAnnonce]
exten => s,1,Playback(accueil)
same => n,Playback(menuIVR)
same => n,WaitExten(5)

exten => 1,1,Dial(PJSIP/FanvilXX,12)
same => n,Hangup()

exten => 2,1,Dial(PJSIP/CiscoXX,12)
same => n,Hangup()

exten => 3,1,SayUnixTime()
same => n,Goto(s,1)

exten => 4,1,Hangup()
exten => i,1,Playback(menuIVR)
same => n,Goto(s,1)
exten => t,1,Playback(menuIVR)
same => n,Goto(s,1)
