; Extrait assaini du trunk SIP inter-sites.

[siptrunk-auth]
type=auth
auth_type=userpass
username=TrunkX
password=<mot-de-passe-masque>

[siptrunk-aor]
type=aor
contact=sip:<ip-serveur-distant>:5060

[siptrunk]
type=endpoint
transport=transport-udp
context=externe_recu
disallow=all
allow=ulaw
direct_media=no
outbound_auth=siptrunk-auth
aors=siptrunk-aor
rtp_symmetric=yes
force_rport=yes

[siptrunk-registration]
type=registration
outbound_auth=siptrunk-auth
server_uri=sip:<ip-serveur-distant>
client_uri=sip:TrunkX@<ip-serveur-distant>
retry_interval=30

[siptrunk-identify]
type=identify
endpoint=siptrunk
match=<ip-serveur-distant>
